package sinbad2.element.campaigns.listener;

public enum ECampaignsChange {
	ADD_CAMPAIGN, SEARCH_CAMPAIGNS, SEARCH_CAMPAIGNS_ALREADY_ADDED, ADD_CAMPAIGNS_SELECTED, REMOVE_CAMPAIGNS_SELECTED, CAMPAIGNS_CHANGES, 
	CAMPAIGNS_SELECTED_CHANGES, FINAL_CAMPAIGNS;
}
